# Generated by Django 6.0.5 on 2026-05-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(default='🌿', help_text='Fallback if no image', max_length=12)),
                ('tagline', models.CharField(help_text='Short one-liner shown on the card', max_length=200)),
                ('description', models.TextField(help_text='Long, comical, shown in the popup')),
                ('category', models.CharField(choices=[('FLOWER', 'Flower'), ('EDIBLE', 'Edible'), ('EXTRACT', 'Extract'), ('ACCESSORY', 'Accessory'), ('MYSTERY', 'Mystery')], default='FLOWER', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
