# Generated by Django 6.0.5 on 2026-05-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('emoji', models.CharField(default='🍿', max_length=12)),
                ('description', models.TextField(help_text='Funny / vivid description')),
                ('difficulty', models.PositiveSmallIntegerField(default=1, help_text='How hard to make while blazed (1=easy, 5=brain surgery)')),
                ('vibe', models.CharField(choices=[('SALTY', 'Salty'), ('SWEET', 'Sweet'), ('CHAOTIC', 'Chaotic'), ('BASIC', 'Basic')], default='SALTY', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
